server:
  port: 8002
spring:
  application:
    name: service-provider-demo
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://172.16.78.110:3306/demo?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    password: XXX
    username: XXX
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2